### ISSUE TITLE
拨号出现这个问题

### ISSUE THREAD

**Issue by FBIX0024** [SinKy-Yan/K2-Netkeeper-OpenWrt#4]
sent [PAP AuthNak id=0x4 "Session started successfully"]
PAP peer authentication failed for ^M1"\R,7 0019501028414
sent [LCP TermReq id=0x2 "Authentication failed"]
rcvd [LCP EchoRep id=0x0 magic=0x3af973f7]
rcvd [LCP TermAck id=0x2 "Authentication failed"]
Connection terminated.
帐号密码拦截成功，显示有网络，但是认证失败了，无法上网，这是什么问题？

**Comment by SinKy-Yan** [comment]
不知道,这个我也很久没弄了
